config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  root "tasks#index"
  patch "tasks/:id/done" => "tasks#done", as: :done_task

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates_presence_of :name, :description
  validates :name, length: { minimum: 2 }
  validates :description, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:edit, :show, :update, :destroy, :done]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    params["task"]["done"] = false
    Task.create(task_params)
    redirect_to root_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to root_path
  end

  def done
    @task.done ? (@task.done = false) : (@task.done = true)
    @task.save
    redirect_to root_path
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :done)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyTodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="my-header">
    <h1>Welcome to your Todo List!</h1>
    <hr>
  </div>

  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/tasks/_form.html.erb
<hr>
<%= simple_form_for(@task) do |f| %>
  <%= f.input :name, label: "What is the name of your task?", placeholder: "Task name" %>
  <%= f.input :description, label: "How would you describe your task?", placeholder: "Task description" %>
  <%= f.submit "Submit", class: "btn btn-success" %>
<% end %>
<br>
<%= link_to "Cancel and go back to Todo List", tasks_path, class: "btn btn-danger" %>

app/views/tasks/edit.html.erb
<div class="card card-task text-center">
  <h2>Edit the task: <%= @task.name %></h2>
  <%= render ("form") %>
</div>

app/views/tasks/index.html.erb
<div class="card card-list text-center">
  <h2>Your tasks are:</h2>
  <%= link_to "Add a new task", new_task_path, class: "btn btn-success" %>
  <br>
  <br>
  <div>
    <table class="tasks-list">
      <tr>
        <th class="text-center">Task</th>
        <th class="text-center">Done?</th>
        <th class="text-center">Edit</th>
        <th class="text-center">Delete</th>
      </tr>
      <% @tasks.each do |task| %>
      <tr>
        <td>
          <%= link_to task.name, task_path(task) %>
        </td>
        <td>
          <% if task.done %>
            <%= link_to done_task_path(task), method: :patch do %><i class="fa fa-check"></i><% end %>
          <% else %>
            <%= link_to done_task_path(task), method: :patch do %><i class="fa fa-times"></i><% end %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_task_path(task) do %><i class="fa fa-pencil"></i><% end %>
        </td>
        <td>
          <%= link_to task_path(task), method: :delete do %><i class="fa fa-trash-o"></i><% end %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="card card-task text-center">
  <h2>Create a new task</h2>
  <%= render ("form") %>
</div>

app/views/tasks/show.html.erb
<div class="card card-task text-center">
  <h2><%= @task.name %></h2>
  <hr>
  <p><%= @task.description %></p>
  <hr>
  <p>
    <% if @task.done %>
      Task already done! <i class="fa fa-check"></i>
    <% else %>
      Task not done yet... <i class="fa fa-times"></i>
    <% end %>
  </p>
  <br>
  <%= link_to "Back to Todo List", tasks_path, class: "btn btn-primary" %>
</div>